version: '3.7'

services:
  db:
    container_name: teacher-administration-system-mysql
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: teacher-administration-system
    ports:
      - "33306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
